### ISSUE TITLE
Reverse translation doesn't work

### ISSUE THREAD

**Issue by mortenivar** [apertium/apertium-nor-eng#1]
This is fine:

```
~/ % echo eple | apertium nob-eng
apple
```
However, doing

`~/ % echo apple | apertium eng-nob`

makes apertium-tagger use 99% of the cpu for about 20 seconds, before giving up with no result.

**Comment by TinoDidriksen** [comment]
That feels like https://github.com/apertium/apertium-init/issues/31

**Comment by mortenivar** [comment]
It is an old problem then. Hopefully to be solved, soon. I am using nor-eng as a template for a dan-eng dictionary.

**Comment by unhammer** [comment]
@mortenivar it's an old problem in init, but fixing it in individual pairs is as easy as adding an ` -x` in the right place. If you used the old modes file from this pair, pick up the new one!
(the problem for init is knowing when it's the right place, really it should be fixed in tagger)

**Comment by mortenivar** [comment]
I got the new modes.xml and it works, sort of. The translated word in the reverse translation is now prefixed with a hash character:

```
~/ % echo apple | apertium eng-nob
#eple

Is there some lt-comp command I should use?

```

**Comment by unhammer** [comment]
No, that's because of a tags mismatch. You could try https://wiki.apertium.org/wiki/Apertium-viewer to see what the pipeline looks like at each step, or manually with `echo apple | apertium eng-nob-XXX` where XXX is e.g. `biltrans` (do `ls modes` to see all possible debug modes). Bokmål tags should probably be `<n><nt><sg><ind>` for this translation. If biltrans output looks right, it needs fixing in [transfer rules](https://wiki.apertium.org/wiki/A_long_introduction_to_transfer_rules) `t[123]x`

**Comment by mortenivar** [comment]
Kevin Brubeck Unhammer ***@***.***> wrote:

> No, that's because of a tags mismatch. You could try
> https://wiki.apertium.org/wiki/Apertium-viewer to see what the
> pipeline looks like at each step, or manually with `echo apple
> | apertium eng-nob-XXX` where XXX is e.g. `biltrans` (do `ls
> modes` to see all possible debug modes). Bokmål tags should
> probably be `<n><nt><sg><ind>` for this translation. If
> biltrans output looks right, it needs fixing in [transfer
> rules](https://wiki.apertium.org/wiki/A_long_introduction_to_transfer_rules)
> `t[123]x`

I don't understand how I can use the debug modes. They are all
created under the modes directory, e.g. "nob-eng-biltrans.mode",
but when use the command above with any of the debug modes,
apertium just spews out a list of modes that are available to
it, and for nob-eng, there are no debug modes available at all,
even if they exist. How can I make apertium see them?

**Comment by mr-martian** [comment]
Use the `-d` option to tell apertium where the source directory is. So `apertium -d . eng-nob-biltrans` will work if you're in the apertium-nor-eng directory or else `apertium -d apertium-nor-eng eng-nob-biltrans` if you're in the directory above it and so on.
