### ISSUE TITLE
Dependency for package version that doesn't exist...

### ISSUE THREAD

**Issue by yeezus9000** [apertium/apertium-nor-eng#2]
Hello! Firstly, the README is static about which package versions are needed, and very outdated. When actually running the makefile, as of today it asks for lttoolbox 3.7.8 (apt has 3.7.6 but manual install can get 3.7.8) and cg3 1.4.8. However... there is no cg3 3.4.8 that I can find anywhere... apt has 1.4.6, and the same is true for the git repo latest release (https://github.com/GrammarSoft/cg3) and I can find no branches with a higher release number.

**Comment by TinoDidriksen** [comment]
[Nightly apt packages](https://apertium.projectjj.com/apt/install-nightly.sh) have lttoolbox 3.7.15 and cg3 1.4.18. When building from source, it is expected you have all the tools either from latest nightly or also from source.

You can also just get apertium-nor-eng from the nightly repo.
